# 生产环境配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bi_video?useSSL=false&serverTimezone=UTC
    username: MoJi
    password: 1535889816
  data:
    redis:
      host: localhost
      port: 6379
      password: 1535889816
      database: 0
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0

file:
  upload:
    root: C:/Users/Administrator/Desktop/bilibili/dist/upload
    comment-img: C:/Users/Administrator/Desktop/bilibili/dist/upload/comment/
    avatar: C:/Users/Administrator/Desktop/bilibili/dist/upload/avatar/
    video-cover: C:/Users/Administrator/Desktop/bilibili/dist/upload/video/cover/
    video: C:/Users/Administrator/Desktop/bilibili/dist/upload/video/
    message-img: C:/Users/Administrator/Desktop/bilibili/dist/upload/message/
    collect-classify: C:/Users/Administrator/Desktop/bilibili/dist/upload/collectClassify/
    background: C:/Users/Administrator/Desktop/bilibili/dist/upload/background/
    dynamic: C:/Users/Administrator/Desktop/bilibili/dist/upload/dynamic/
